pipeline
{
    agent any
    stages
    {
        stage("Clean Workspace")
        {
            steps
            {
                cleanWs()
            }
        }

        stage("Git Checkout")
        {
            steps
            {
                git branch: 'qa_master', credentialsId: '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', url: "https://github.com/adish231091/QA.git"
            }
        }

        stage("Execute script")
        {
            steps
            {
                script
                {
                    def para1 = params.variable1
                    def para2 = params.variable2
                    def path = "/Users/adishsharma/Desktop/mavenQA/QA/maven_test/src/main"
                    sh "sh ${env.WORKSPACE}/maven_test/src/main/test.sh ${para1} ${para2} ${env.WORKSPACE}"
                }
            }
        }
    }

    post
    {
        success
        {
            echo "Always run"
        }

        failure
        {
            echo "Always run if it fail also"
        }
    }
}