pipeline
{
    agent any
    stages
    {
        stage("Clean Workspacess")
        {
            steps
            {
                cleanWs()
            }
        }
        stage("Tests Polling")
        {
            steps
            {
                echo "commit happen , build started !!!!"
            }
        }
    }
}